server:
  port: 10010

spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 3077ab72-eaab-4e45-8c6a-165fa754377a
    gateway:
      routes:
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/user/**

        - id: order-server
          uri: lb://order-server
          predicates:
            - Path=/order/**
          filters:
            - AddRequestHeader=name,gaohonghao
      default-filters:
        - AddRequestHeader=girl,mayingxin